### ISSUE TITLE
How to administer users after startup?

### ISSUE THREAD

**Issue by welchwilmerck** [UMMS-Biocore/dolphinnext-docker#46]
I get the container started and get to the login page.  Then, 'sign up'.  Then, go into the backend and `update users set active=1, role='admin'  where id = 1;`.  I'm OK from there, but it seems like I'm missing some bootstrap script or process.

**Comment by nephantes** [comment]
Can you set the first user admin in DB? This user will then me the admin.

**Comment by welchwilmerck** [comment]
That works!

**Comment by vkaimal** [comment]
I'm having a similar issue after startup, but not even getting as far as @welchwilmerck. I click on"Sign Up" and it times out. I logged into the DB and created a new user (admin with 'admin' role and active=1), but it still doesn't login. I did leave the 'logintype' and 'verification' fields in the DB empty, perhaps that's why? Not sure why neither Sign Up nor login are working. Any tips would be great. Thanks!

**Comment by nephantes** [comment]
Without defining anything, could you try to login with your google account? The first user you logged in will be the admin. We have actually fixed that problem. Without defining anything in DB. it should work.

**Comment by onuryukselen** [comment]
You shouldn't add a user from db, it might cause other problems. I suggest you delete that first user from db and send the apache log by checking following file in docker:
cat /var/log/apache2/error.log
There must be an issue while signing up.

**Comment by vkaimal** [comment]
@nephantes I tried with a Google account, but since I'm hosting this on a private EC2 instance, the authentication is not being allowed. Any workarounds? @onuryukselen, I have deleted the user from the DB. Not much in the apache error log:

`[Thu Apr 23 18:37:41.517071 2020] [mpm_prefork:notice] [pid 742] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Thu Apr 23 18:37:41.517112 2020] [core:notice] [pid 742] AH00094: Command line: '/usr/sbin/apache2'
[Fri Apr 24 15:18:11.429814 2020] [core:warn] [pid 996] AH00098: pid file /var/run/apache2/apache2.pid overwritten -- Unclean shutdown of previous Apache run?
[Fri Apr 24 15:18:11.432425 2020] [mpm_prefork:notice] [pid 996] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Fri Apr 24 15:18:11.432443 2020] [core:notice] [pid 996] AH00094: Command line: 'apache2 -D FOREGROUND'`

**Comment by onuryukselen** [comment]
@vkaimal Can you please send e-mail to **support@dolphinnext.com** and describe the problem you encountered when you've tried to sign-up? Also, please complete the following information:
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Comment by vkaimal** [comment]
@onuryukselen I have sent the email. Please let me know if I can provide any additional information. Thanks

**Comment by onuryukselen** [comment]
@nephantes Issue fixed by changing /export/dolphinnext/config/.sec file.  You can close the issue now.

```
BASE_PATH = http://localhost:8080/dolphinnext
PUBWEB_URL = http://localhost:8080/dolphinnext/tmp/pub
```

to
```
BASE_PATH = http://your_temporary_domain_name:8080/dolphinnext
PUBWEB_URL = http://your_temporary_domain_name:8080/dolphinnext/tmp/pub
```
* Please don’t change other lines because others are used inside of docker.

We define localhost:8080 in config/.sec file and using that to log in. Without changing those localhost lines to that IP address or amazon domain you use, it won’t work. So you need to have static IP address would solve the issue that you will not need to change it every time.
